--- PRACTICA JOINS
--CREAR CON COMANDOS DDL UNA ENTIDAD PADRE
CREATE TABLE PADRE(
    ID_PADRE NUMBER,
    NOMBRE NVARCHAR2(100),
    APELLIDO NVARCHAR2(100),
    EDAD NUMBER,
    TRABAJO NVARCHAR2(100),
    CONSTRAINT PADRE_PK PRIMARY KEY(ID_PADRE)
);

INSERT INTO PADRE VALUES(1, 'OSCAR', 'SANCHEZ', 38, 'CHOFER');
INSERT INTO PADRE VALUES(2, 'LUIS', 'RAMIREZ', 40, 'MECANICO');
INSERT INTO PADRE VALUES(3, 'PEDRO', 'ROMERO',54,'SUPERVISOR');
INSERT INTO PADRE VALUES(4,'ALEJANDRO','PEREZ',42,'OBRERO');
INSERT INTO PADRE VALUES(5,'ISRAEL', 'GOMEZ', 36, 'ARQUITECTO');
INSERT INTO PADRE VALUES(6,'JORGE','CANDELARIO',35,'PROFESOR');
COMMIT;

SELECT * FROM PADRE;

--CREAR TABLA HIJO
CREATE TABLE HIJO(
    ID_HIJO NUMBER,
    NOMBRE NVARCHAR2(100),
    APELLIDO NVARCHAR2(100),
    EDAD NUMBER,
    HOBBIE NVARCHAR2(100),
    PADRE_ID NUMBER,
    CONSTRAINT HIJO_PK PRIMARY KEY(ID_HIJO),
    CONSTRAINT HIJO_FK FOREIGN KEY(PADRE_ID) REFERENCES PADRE(ID_PADRE)
);

INSERT INTO HIJO VALUES(1, 'DANIEL', 'GOMEZ', 13, 'FUTBOL', 5);
INSERT INTO HIJO VALUES(2, 'ANA', 'MENDEZ', 16, 'BAILAR', NULL);
INSERT INTO HIJO VALUES(3,'LUIS','SANCHEZ',12,'ESCALAR',1);
INSERT INTO HIJO VALUES(4,'SANDRA','CURIEL',16,'PATINAR',3);
INSERT INTO HIJO VALUES(5, 'GUILLERMO', 'GOMEZ', 8, 'MUSICA', 5);
INSERT INTO HIJO VALUES(6, 'YAIR', 'SANCHEZ', 10, 'VIDEOJUEGOS', 1);
INSERT INTO HIJO VALUES(7, 'JUAN', 'RAMIREZ', 17, 'BOX', 2);
INSERT INTO HIJO VALUES(8, 'HECTOR', 'JUAREZ', 8, 'BEISBALL', NULL);
INSERT INTO HIJO VALUES (9,'MISAEL','CANDELARIO',10,'BASKETBALL',6);
INSERT INTO HIJO VALUES (10,'EMMA','CANDELARIO',6,'BAILAR',6);
INSERT INTO HIJO VALUES(11,'CRISTIAN','CANDELARIO',11,'MUSICA',6);
INSERT INTO HIJO VALUES(12,'JORDAN','ROMERO',7,'DIBUJAR',3);
COMMIT;

SELECT * FROM HIJO;

--USO DEL INNER JOIN -------------> TODAS LAS COINCIDENCIAS DE LA TABLA A Y B (MATCH)
SELECT * FROM 
HIJO H INNER JOIN PADRE P
ON H.PADRE_ID = P.ID_PADRE;

--LEFT JOIN ---------------> TODAS LAS COINCIDENCIAS(INNER) Y LAS NO COINCIDENCIAS DE LA TABLA (HIJO)
SELECT * FROM 
HIJO H LEFT JOIN PADRE P
ON H.PADRE_ID = P.ID_PADRE;

--LEFT JOIN -----------------> CON LAS NO COINCIDENCIAS
SELECT * FROM 
HIJO H LEFT JOIN PADRE P
ON H.PADRE_ID = P.ID_PADRE
WHERE H.PADRE_ID IS NULL;

--RIGHT JOIN ------------------> TODAS LAS COINCIDENCIAS(INNER) Y LAS NO COINCIDENCIAS DE LA TABLA B(PADRE)
SELECT * FROM 
HIJO H RIGHT JOIN PADRE P
ON H.PADRE_ID = P.ID_PADRE;

--RICGHT JOIN SOLO CON NO COINCIDENCIAS
SELECT * FROM 
HIJO H RIGHT JOIN PADRE P
ON H.PADRE_ID = P.ID_PADRE
WHERE H.PADRE_ID IS NULL;

--USO DE JOIN 
SELECT * FROM 
HIJO H FULL JOIN PADRE P
ON H.PADRE_ID = P.ID_PADRE;

--FULL JOIN EXCLUYENTE
SELECT * FROM HIJO H
FULL JOIN PADRE P
ON H.PADRE_ID = P.ID_PADRE
WHERE H.PADRE_ID IS NULL
OR P.ID_PADRE IS NULL;

