--DML
SELECT * FROM EMPLEADO;

INSERT INTO EMPLEADO VALUES(1, 'PEDRO', 'FERNANDEZ', 28, 'DESARROLLADOR JAVA', 'DEP. IT');
INSERT INTO EMPLEADO VALUES(2, 'ALEJANDRA', 'MORA', 27, NULL, NULL);
INSERT INTO EMPLEADO VALUES (3,'ERIK','SANCHEZ',26,'DISEÑADOR WEB','DEP. WEB');
INSERT INTO EMPLEADO VALUES (4,'SAMANTHA','MORALES',22,'DESARROLLADOR JAVA','DEP. IT');
INSERT INTO EMPLEADO VALUES(5, 'SAID', 'MOYA', 23, 'PRACTICANTE JAVA', 'IT');
INSERT INTO EMPLEADO VALUES(6, 'PAULINA', 'VILLANUEVA', 25, 'CONTADORA', 'FINANZAS');
INSERT INTO EMPLEADO VALUES(7, 'JUAN', 'CAMPO',23,'ANALISTA','DEP. IT');
INSERT INTO EMPLEADO VALUES(8, 'ROSA', 'DIAZ',30,'JEFA','DEP. RH');
INSERT INTO EMPLEADO VALUES(9, 'BRENDA','QUIJANO',21,'RECLUTADORA','RECURSOS HUMANOS');
INSERT INTO EMPLEADO VALUES(10, 'KARINA','ROMAN',25,'ANALISTA','ADMINISTRACION');
INSERT INTO EMPLEADO VALUES(11,'HECTOR','PEREZ',24,'RECULTADOR','DEPT. RH');
INSERT INTO EMPLEADO VALUES(12,'LALO','FLORES',30,'DESARROLLADOR','DEPT. WEB');

COMMIT;
SELECT * FROM EMPLEADO;

--MODIFICAR CON UN DDL EL NOMBRE DE LA COLUMNA O CAMPO
ALTER TABLE EMPLEADO RENAME COLUMN AP TO APELLIDO;

--UPDATE ---DML
UPDATE EMPLEADO SET DEPARTAMENTO = 'DEP. IT' WHERE ID_EMPLEADO = 3;

--ORDER BY
SELECT * FROM EMPLEADO ORDER BY EDAD ASC; --ASCEDENTE
SELECT * FROM EMPLEADO ORDER BY EDAD DESC;

--BUSQUEDA DE INFORMACION CON CARACTERES ESPECIFICOS
--BUSCAR EMPLEADO QUE COMIENCEN CON LA LETRA 'A'
SELECT * FROM EMPLEADO WHERE NOMBRE LIKE 'A%';

--BUSCAR EMPLEADOS QUE CONTENGAN EN SU NOMBRE ALGUNA LETRA 'I'
SELECT * FROM EMPLEADO WHERE NOMBRE LIKE '%I%';

--BUSCAR EMPLEADOS QUE SU NOMBRE FINALICE CON LA LETRA 'O'
SELECT * FROM EMPLEADO WHERE NOMBRE LIKE '%O';

--BUSCAR EMPLEADOS QUE EN SU PUESTO SEA NULL
SELECT * FROM EMPLEADO WHERE PUESTO IS NULL;

--USO DE LA TABLA DUAL
SELECT 5 + 5 AS SUMA FROM DUAL;

--USO DE LA FUNCION LENGTH
SELECT LENGTH('ESTA ES UNA CAENA DE PRUEBA PARA EL USO DE LENTH') AS TAMANIO FROM DUAL;

--BUSCAR LOS EMPLEADOS MAYORES A 26 AÑOS
SELECT * FROM EMPLEADO WHERE EDAD > 26;

--BUSCAR LOS EMPLEADOS MENORES A 25 AÑOS
SELECT * FROM EMPLEADO WHERE EDAD < 25;

--bUSCAR POR RANGO
SELECT * FROM EMPLEADO WHERE EDAD BETWEEN 23 AND 30;

--BUSCAR LOS EMPLEADOS CON EL ID = 1,3,5 Y 7
SELECT * FROM EMPLEADOS WHERE ID_EMPLEADO = 1 OR ID_EMPLEADO = 3 OR ID_EMPLEADO = 5 OR ID_EMPLEADO = 7;

--USO DE LA FUNCION IN
SELECT * FROM EMPLEADO WHERE ID_EMPLEADO IN(1,3,5,7);