SELECT * FROM COMPUTADORA;
SELECT * FROM BUT_COMPUTADORA;

INSERT INTO COMPUTADORA VALUES (1,'HP','VICTUS',16,'INTEL CORE i7',25000);
INSERT INTO COMPUTADORA VALUES (2,'MSI','KATANA',16,'INTEL CORE I7',30000);
