/*
3 tipos de comandos:

DDL: Lenguaje de definicion de datos -> comandos utilizadas para estructurar datos: CREATE, DROP, TRUNCATE Y ALTER
DML: Lenguaje de manipulacion de datos -> comandos que se utuliza para manipular los datos: INSERT, UPDATE, DELETE Y SELECT
DCL: Lenguaje de control de datos -> comandos que sirven para controlar los permisos: GRANT Y REVOKE

*/

-- COMANDOS DDL
CREATE TABLE EMPLEADO(
    ID_CLIENTE NUMBER,
    NOMBRE NVARCHAR2(100),
    AP NVARCHAR2(100),
    EDAD NUMBER,
    PUESTO NVARCHAR2(100),
    DEPARTAMENTO NVARCHAR2(100)
);



--COMANDO DML
INSERT INTO EMPLEADO VALUES(1,'ROBERTO','ROJAS',35,'PROGRAMADOR JAVA','DEP.IT');

/* CADAVEZ QUE SE EJECUTE UNA SENTENCIA DML: (iNSERTT, UPDATE O DELETE), DEBEMOS CONFIRMAR LOS CAMBIOS PARA TERMINAR CON LA TRANSACCION REALIZAD.
 SI UNA TRANSACCION DE QUEDA SIN CONFIRMAR LA DB QUEDARA BLOQUEADA PPOR EL USUARIO QUE REALIZO LA SENTENCIA Y NINGUN OTRO PODRA REALIZAR OPERACIONES
 DE PERSISTENCIA EN LA BD*/
 
 COMMIT; --CONFIRMAR LOS CAMBIOS
 ROLLBACK; --REVIERTE LOS CAMBIOS
 
 --DML PARA ELIMINAR
 DELETE FROM EMPLEADO WHERE ID_CLIENTE = 1;
 
 --DDL PARA ELIMINAR
 DROP TABLE EMPLEADO;
 SELECT * FROM EMPLEADO;
 
 --CONSTRAINT: SON RESTRICCIONES QUE SE APLICAN A UNA ENTIDAD PARA GARANTIZAR LA INTEGRIDAD, CONSISTENCIA Y LA VALIDEZ DE LOS DATOS ALMACENADOS
 --DDL CON PRYMARY KEY ---> PRIMERA FORMA
 CREATE TABLE EMPLEADO(
    ID_EMPLEADO NUMBER,
    NOMBRE NVARCHAR2(100),
    AP NVARCHAR2(100),
    EDAD NUMBER,
    PUESTO NVARCHAR2(100),
    DEPARTAMENTO NVARCHAR2(100),
    PRIMARY KEY(ID_EMPLEADO)
 );
 
 -- SEGUNDA FORMA
 CREATE TABLE EMPLEADO(
    ID_EMPLEADO NUMBER PRIMARY KEY,
    NOMBRE NVARCHAR2(100)
 );
 
 --TERCER FORMA ---------> CONTSRAINT + NOMBRE_CONSTRAINT(TABLA+PK)+PRIMARY KEY + CAMPO QUE SERA LA CLAVE
 CREATE TABLE EMPLEADO(
    ID_EMPLEADO NUMBER,
    NOMBRE NVARCHAR2(100),
    AP NVARCHAR2(100),
    EDAD NUMBER,
    PUESTO NVARCHAR2(100),
    DEPARTAMENTO NVARCHAR2(100),
    CONSTRAINT EMPLEADO_PK PRIMARY KEY(ID_EMPLEADO)
 );
 
 SELECT * FROM EMPLEADO;
 
