--TRIGGER A NIVEL SENTENCIA
--CREAR TRIGGER A NIVEL SENTENCIA PARA LA TABLA COMPUTADORA
CREATE OR REPLACE TRIGGER TR_I_U_D_COMPUTADORA
AFTER INSERT OR UPDATE OR DELETE ON COMPUTADORA
DECLARE
LV_ID_BIT NUMBER;
LV_USUARIO NVARCHAR2(100);
LV_FECHA DATE;
LV_MOV NVARCHAR2(100);
BEGIN

    SELECT S_ID_BIT.NEXTVAL, USER, SYSDATE INTO LV_ID_BIT, LV_USUARIO, LV_FECHA FROM DUAL;
    
    IF INSERTING THEN
        LV_MOV := 'insert';
    ELSIF UPDATING THEN
        LV_MOV := 'update';
    ELSIF DELETING THEN
        LV_MOV := 'delete';
    END IF;
    
    INSERT INTO BUT_COMPUTADORA(ID_BIT,USUARIO,FECHA_MOV,MOVIMIENTO)
    VALUES(LV_ID_BIT,LV_USUARIO,LV_FECHA,LV_MOV);
END TR_I_U_D_COMPUTADORA;
/