-- CASE

/*
CASE
    WHEN CONDICION_1 THEN RESULTADO_1
    WHEN CONDICION_2 THEN RESULTADO_2
    ............
    ELSE RESULTADO_PREDETERMINADO
END
*/

--COMANDO DDL ------------> ENTIDAD LIBRO
CREATE TABLE LIBRO(
    ID_LIBRO NUMBER,
    NOMBRE NVARCHAR2(100),
    AUTOR NVARCHAR2(100),
    GENERO NUMBER,  --1 DRAMA, 2 COMEDIA, 3 CIENCIA, 4 NOVELA, 5 TERROR
    NO_PAGINAS NUMBER,
    PRECIO NUMBER,
    EDITORIAL NVARCHAR2(100),
    CONSTRAINT LIBRO_PK PRIMARY KEY(ID_LIBRO)
);
DROP TABLE LIBRO;
COMMIT;
INSERT INTO LIBRO VALUES(1, 'CIEN AÑOS DE SOLEDAD', 'GABRIEL GARCIA MARQUEZ', 1, 280, 500, 'EDICIONES SALAMANDRA');
INSERT INTO LIBRO VALUES(2, 'EL PRINCIPITO', 'ANTOINE DE SAINT-EXUPERY', NULL, 120, 130, 'LANDUCCI');
INSERT INTO LIBRO VALUES(3, 'PEDRO PÁRAMO', 'JUAN RULFO', 4, 124, 300, 'FONDO DE CULTURA');
INSERT INTO LIBRO VALUES(4, 'ARRÁNCAME LA VIDA', 'ÁNGELES MASTRETTA', 4, 304, 350, 'EDITORIAL DREAMERS');
INSERT INTO LIBRO VALUES(5, 'LAS BATALLAS EN EL DESIERTO', 'JOSE EMILIO PACHECO', 1, 68, 150, 'EDICIONES ERA');
INSERT INTO LIBRO VALUES(6, 'LA METAMORFOSIS', 'FRANZ KAFKA', 4, 201, 250, 'EDICIONES ALIANZA');
INSERT INTO LIBRO VALUES(7,'DRACULA','BRAM STOKER',5,400,300,'ARCHIBALD COMPANY');
INSERT INTO LIBRO VALUES(8,'IT','STEPHEN KING',5,700,500,'VIKING PRESS');
INSERT INTO LIBRO VALUES(9,'Mein Kampf', 'Adolf Hitler',3,781,599,'Secker and Warburg');
INSERT INTO LIBRO VALUES(10,'La Quimica del amor', ' Ali Hazelwood',4,480,650,'‎Contraluz');
INSERT INTO LIBRO VALUES(11, 'THE MIST','STEPHEN KING',5,320,269,'DEBOLSILLO');
INSERT INTO LIBRO VALUES(12, 'IT','STEPHEN KING',5,1504,679,'DEBOLSILLO');

SELECT * FROM LIBRO;

SELECT ID_LIBRO,NOMBRE,AUTOR,(
    CASE GENERO
        WHEN 1 THEN 'DRAMA'
        WHEN 2 THEN 'COMEDIA'
        WHEN 3 THEN 'CIENCIA FICCION'
        WHEN 4 THEN 'NOVELA'
        WHEN 5 THEN 'TERROR'
        ELSE 'SIN GENERO'
    END
) AS GENERO, NO_PAGINAS, PRECIO, EDITORIAL FROM LIBRO;

SELECT ID_LIBRO, NOMBRE, AUTOR, GENERO, NO_PAGINAS,(
    CASE
    WHEN PRECIO > 500 THEN 'ES CARO' || TO_CHAR(PRECIO, 'FM$9,999.00') || 'PESOS'
    WHEN PRECIO <= 500 THEN 'ES BARATO' || TO_CHAR(PRECIO,'FM$9,999.00')||'PESOS'
    ELSE 'PRECIO NO DEFINIDO'
    END
) AS PRECIO, EDITORIAL FROM LIBRO;
