-- Modificar la sesion actual para la ejecucion de scripts
ALTER SESSION SET "_ORACLE_sCRIPT" = TRUE;

--CREACION DEL USUARIO Y CONTRASEÑA
CREATE USER ORCL IDENTIFIED BY Curso2024;

--OTORGAR PERMISOS DE ADMINISTRADOR AL NUEVO USUARIO
GRANT ALL PRIVILEGES TO ORCL;

--asi se crea un usuario