--SECUENCIA NUEVA
--CREAR UNA SECUENCIA PARA ''ID_BIT'' DE LA TABLA BIT_COMPUTADORA

CREATE SEQUENCE S_ID_BIT
START WITH 3
INCREMENT BY 1
MAXVALUE 99999
MINVALUE 1
NOCYCLE; ---- SI TERMINA NO SE VUELVE A REINICIAR
/

DROP SEQUENCE S_ID_BIT;

SELECT * FROM BUT_COMPUTADORA;

SELECT S_ID_BIT.NEXTVAL FROM DUAL;