--DESACTIVAR TRIGGER

ALTER TRIGGER TR_U_COMPUTADORA DISABLE;

--ACTIVAR TRIGGER
ALTER TRIGGER TR_U_COMPUTADORA ENABLE;


--TRIGGER MULTIPLE
CREATE OR REPLACE TRIGGER TR_MULTIPLE_COMPUTADORA
AFTER INSERT OR UPDATE OR DELETE ON COMPUTADORA
FOR EACH ROW
DECLARE
LV_ID_BIT NUMBER;
LV_USUSARIO NVARCHAR2(100);
LV_FECHA DATE;
BEGIN
--RECUPERAR INFORMACION PARA VARIABLE DE CONTROL
    SELECT S_ID_BIT.NEXTVAL, USER,SYSDATE INTO LV_ID_BIT, LV_USUSARIO, LV_FECHA FROM DUAL;   

    IF INSERTING THEN
        INSERT INTO BUT_COMPUTADORA(ID_BIT,ID_COMPU,MARCA,MODELO,RAM,PROCESADOR,PRECIO,MARCA_OLD,MODELO_OLD,RAM_OLD,PROCESADOR_OLD,PRECIO_OLD,USUARIO,FECHA_MOV,MOVIMIENTO)
    
                             VALUES(LV_ID_BIT, :NEW.ID_COMPU, :NEW.MARCA, :NEW.MODELO,:NEW.RAM, :NEW.PROCESADOR, :NEW.PRECIO,NULL,NULL,0,NULL,0,LV_USUSARIO, LV_FECHA,'INSERT');
    
    ELSIF UPDATING THEN
        INSERT INTO BUT_COMPUTADORA(ID_BIT,ID_COMPU,MARCA,MODELO,RAM,PROCESADOR,PRECIO,MARCA_OLD,MODELO_OLD,RAM_OLD,PROCESADOR_OLD,PRECIO_OLD,USUARIO,FECHA_MOV,MOVIMIENTO)
    
                             VALUES(LV_ID_BIT,:OLD.ID_COMPU,:NEW.MARCA,:NEW.MODELO,:NEW.RAM,:NEW.PROCESADOR,:NEW.PRECIO,:OLD.MARCA,:OLD.MODELO,:OLD.RAM,:OLD.PROCESADOR,:OLD.PRECIO,LV_USUSARIO,LV_FECHA,'UPDATE');
    ELSIF DELETING THEN
        INSERT INTO BUT_COMPUTADORA(ID_BIT,ID_COMPU,MARCA,MODELO,RAM,PROCESADOR,PRECIO,MARCA_OLD,MODELO_OLD,RAM_OLD,PROCESADOR_OLD,PRECIO_OLD,USUARIO,FECHA_MOV,MOVIMIENTO)
                
                             VALUES(LV_ID_BIT,:OLD.ID_COMPU,NULL,NULL,NULL,NULL,NULL,:OLD.MARCA,:OLD.MODELO,:OLD.RAM,:OLD.PROCESADOR,:OLD.PRECIO,LV_USUSARIO,LV_FECHA,'DELETE');

    END IF;
END TR_MULTIPLE_COMPUTADORA;
/



SELECT * FROM BIT_COMPUTADORA;
SELECT * FROM COMPUTADORA;

INSERT INTO COMPUTADORA VALUES(1,'APPLE','MAC',16,'APPLE',22000);
INSERT INTO COMPUTADORA VALUES(2,'NUEVA MARCA', 'NUEVO MODELOR',32,'RYZEN 9',32000);

DELETE FROM COMPUTADORA;
SELECT * FROM COMPUTADORA;
SELECT * FROM BUT_COMPUTADORA;

SELECT USER FROM DUAL;
SELECT SYSDATE FROM DUAL;
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY HH24:MI:SS';
